name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm Test
  build:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: action/checkout@v3
    - name: use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Deploy to Render
      run: | 
        curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK }}  